    def test_dot_signature(self):
        self.turtle.dot()
        self.turtle.dot(10)
        self.turtle.dot(size=10)
        self.turtle.dot((0, 0, 0))
        self.turtle.dot(size=(0, 0, 0))
        self.turtle.dot("blue")
        self.turtle.dot("")
        self.turtle.dot(size="blue")
        self.turtle.dot(20, "blue")
        self.turtle.dot(20, "blue")
        self.turtle.dot(20, (0, 0, 0))
        self.turtle.dot(20, 0, 0, 0)
        with self.assertRaises(TypeError):
            self.turtle.dot(color="blue")
        self.assertRaises(turtle.TurtleGraphicsError, self.turtle.dot, "_not_a_color_")
        self.assertRaises(turtle.TurtleGraphicsError, self.turtle.dot, 0, (0, 0, 0, 0))
        self.assertRaises(turtle.TurtleGraphicsError, self.turtle.dot, 0, 0, 0, 0, 0)
        self.assertRaises(turtle.TurtleGraphicsError, self.turtle.dot, 0, (-1, 0, 0))
        self.assertRaises(turtle.TurtleGraphicsError, self.turtle.dot, 0, -1, 0, 0)
        self.assertRaises(turtle.TurtleGraphicsError, self.turtle.dot, 0, (0, 257, 0))
        self.assertRaises(turtle.TurtleGraphicsError, self.turtle.dot, 0, 0, 257, 0)