    def _get_matrix(self,
                    landmarks: npt.NDArray[np.float32],
                    bboxes: npt.NDArray[np.int32],
                    roi_matrices: npt.NDArray[np.float32]) -> np.ndarray:
        """Obtain the (N, 3, 3) transformation matrix to align the landmarks in normalized space
        and add to :attr:`_matrices`

        The matrix:
          - takes the standard matrix that aligns the face/image via umeyama
          - Pads it to better line up with a detection bounding box
          - Adjusts with further padding/offsetting based on the plugin's generated ROI output

        Parameters
        ----------
        landmarks
            The first pass detected landmarks in normalized space
        bboxes
            The original face detection bounding boxes
        roi_matrices
            The original matrices used to map the original square ROIs generated by the plugin back
            to frame space

        Returns
        The (N, 3, 3) transformation matrix that will create an image patch for re-alignment
        """
        # Frame space -> Normalized Space -> Aligned space -> Patch Space
        # normalized -> aligned
        mats = batch_umeyama(landmarks[:, 17:], self._mean_face, True).astype("float32")

        # normalized -> patch
        # Get plugin adjustments
        roi_sizes = roi_matrices[:, 0, 0, None]
        box_sizes = (bboxes[:, 2:] - bboxes[:, :2]).max(axis=1)[..., None]
        bb_to_roi_scales = box_sizes / roi_sizes   # (N, 1)

        roi_center = roi_matrices[:, :2, 2] + (0.5 * roi_sizes)
        bbox_center = (bboxes[:, :2] + bboxes[:, 2:]) / 2.
        bb_to_roi_shifts = (bbox_center - roi_center) / box_sizes

        # Convert plugin adjustment to matrix
        adj_mat = np.repeat(np.eye(3, dtype="float32")[None, :, :], mats.shape[0], axis=0)
        adj_mat[:, 0, 0] = bb_to_roi_scales[:, 0]
        adj_mat[:, 1, 1] = bb_to_roi_scales[:, 0]
        adj_mat[:, :2, 2] = (1 - bb_to_roi_scales) / 2 + bb_to_roi_shifts

        # Combine plugin and default adjustments + scale
        patch_mat = adj_mat @ self._adjust_matrix
        patch_mat[:, :2] *= self._expanded_size

        # Store the matrix that takes expanded space to frame space for updating in get_images
        self._matrices = (roi_matrices @
                          np.linalg.inv(mats) @
                          np.linalg.inv(patch_mat)).astype("float32")
        # Return the matrix that creates the expanded image sub-crop
        return patch_mat @ mats @ np.linalg.inv(roi_matrices)